version: '3.3'

networks:
  actnow:
    external:
      name: actnow
    driver: bridge

services:
  backend:
    image: ar4ikov/actnow-backend:latest
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - '8080:8080'
    expose:
        - '8080'
    networks:
        - actnow
    depends_on:
        - db
    volumes:
        - ./uploads:/app/uploads
    env_file:
        - .env

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'actnow'
      MYSQL_USER: 'host'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '6612:3306'
    networks:
      - actnow
    volumes:
      - ./mysql_db:/var/lib/mysql
