version: '3'

networks:
  actnow:
    driver: bridge

services:
  backend:
    image: ar4ikov/actnowbackend:latest
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - '8080:80'
    networks:
        - actnow
    depends_on:
        - db
    volumes:
        - ./uploads:/app/uploads
    env_file:
        - .env

  db:
    image: postgres:15.2
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "actnow"
      POSTGRES_USER: "actnow"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: on-failure
    volumes:
      - .:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432"
    networks:
      - actnow